apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-persons-api
  name: udaconnect-persons-api
spec:
  ports:
  - name: "5002"
    port: 5002
    targetPort: 5002
    nodePort: 30002
  selector:
    service: udaconnect-persons-api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-persons-api
  name: udaconnect-persons-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-persons-api
  template:
    metadata:
      labels:
        service: udaconnect-persons-api
    spec:
      containers:
      - image: stefanjaindl/udaconnect-persons-api:v1.0.0
        name: udaconnect-persons-api
        imagePullPolicy: Always
        command: [ "/bin/sh", "-c", "env" ]
        envFrom:
          # Load the Complete ConfigMap
          - configMapRef:
              name: db-env
        # env:
        # - name: DB_USERNAME
        #   valueFrom:
        #     configMapKeyRef:
        #       name: db-env
        #       key: DB_USERNAME
        # - name: DB_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: db-secret
        #       key: DB_PASSWORD
        # - name: DB_NAME
        #   valueFrom:
        #     configMapKeyRef:
        #       name: db-env
        #       key: DB_NAME
        # - name: DB_HOST
        #   valueFrom:
        #     configMapKeyRef:
        #       name: db-env
        #       key: DB_HOST
        # - name: DB_PORT
        #   valueFrom:
        #     configMapKeyRef:
        #       name: db-env
        #       key: DB_PORT
      restartPolicy: Always
